backend:
  name: github
  repo: truecodersio/learn.truecoders.io
media_folder: static/assets
collections:
  - name: learn
    label: Learn
    folder: learn
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Module
        name: module
        widget: select
        options:
          - label: Architecture
            value: architecture
          - label: C#
            value: csharp
          - label: Git
            value: git
          - label: Java
            value: java
          - label: SQL
            value: sql
      - label: Order
        name: order
        widget: number
        default: 0
        valueType: int
        min: 0
      - label: Body
        name: body
        widget: markdown
